package postgres

import (
	"context"
	"database/sql"
	"fmt"
	"spender-backend/v2/internal/domain"

	"github.com/lib/pq"
)



type UserRepo struct {
	db *sql.DB
}

// NewUserRepo injects the database connection pool
func NewUserRepo(db *sql.DB) *UserRepo {
	return &UserRepo{db: db}
}

// CreateUser inserts a new user and returns the generated ID and Timestamp
func (r *UserRepo) CreateUser(ctx context.Context, user *domain.User) error {
	// We use 'RETURNING' to get the values generated by Postgres (ID and CreatedAt)
	query := `
		INSERT INTO users (email, password_hash) 
		VALUES ($1, $2) 
		RETURNING id, created_at`

	err := r.db.QueryRowContext(ctx, query, user.Email, user.Password).Scan(&user.ID, &user.CreatedAt)
	if err != nil {
		// Check if it's a Postgres error
		if pgErr, ok := err.(*pq.Error); ok {
			if pgErr.Code == "23505" { // Unique violation code
				return domain.ErrDuplicateEmail // Define this in your domain
			}
		}
		return fmt.Errorf("failed to insert user: %w", err)
	}

	return nil
}

// GetUserByEmail finds a user by their email address
func (r *UserRepo) GetUserByEmail(ctx context.Context, email string) (*domain.User, error) {
	user := &domain.User{}
	query := `
		SELECT id, email, password_hash, created_at 
		FROM users 
		WHERE email = $1`

	err := r.db.QueryRowContext(ctx, query, email).Scan(
		&user.ID,
		&user.Email,
		&user.Password,
		&user.CreatedAt,
	)

	if err != nil {
		if err == sql.ErrNoRows {
			return nil, nil // Or return a custom "not found" error
		}
		return nil, fmt.Errorf("failed to query user: %w", err)
	}

	return user, nil
}
